parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Williarin\WordpressInteropBundle\Bridge\ManagerRegistry:
        arguments:
            $managers: '%wordpress_interop.entity_managers%'
            $defaultManager: '%wordpress_interop.default_entity_manager%'

    Williarin\WordpressInterop\ManagerRegistryInterface: '@Williarin\WordpressInteropBundle\Bridge\ManagerRegistry'

    Williarin\WordpressInterop\EntityManagerInterface: '@wordpress_interop.entity_manager'

    wordpress_interop.entity_manager.abstract:
        class: Williarin\WordpressInterop\EntityManager
        abstract: true
        lazy: true
        factory: ['Williarin\WordpressInterop\EntityManager', 'create']

    serializer.normalizer.serialized_array:
        class: Williarin\WordpressInterop\Serializer\SerializedArrayDenormalizer
        arguments: ['@serializer.normalizer.object']
